### ISSUE TITLE
SSO - 404

### ISSUE THREAD

**Issue by hegedussz** [bitwarden/helm-charts#38]
### Steps To Reproduce

1. Go to 'https://bitwarden/#/sso
2. Click on 'Login.'
3. Login with SSO (SAML 2)

Log:
self-host-web pod 
```
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://bitwarden.xxxx.xx/Account/Login?ReturnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3Dweb%26redirect_uri%3Dhttps%253A%252F%252Fbitwarden.xxxx.xx%252Fsso-connector.html%26response_type%3Dcode%26scope%3Dapi%2520offline_access%26state%3DzPXULyXRcXD5hdeh4kEZtjDgF9fH5ULPL3giu4GDNR7JSgwh896a4a2BhfTXvFF9_identifier%253DKIF%25C3%259C%26code_challenge%3D4YNnYCgAKaCVZYu_mljIsSgWcPdQC1kP38mMRbeZA8o%26code_challenge_method%3DS256%26response_mode%3Dquery%26domain_hint%3DKIF%25C3%259C%26ssoToken%3DBWUserPrefix_CfDJ8MIpcSLm3NdOhzBWDFQa2p_ExYcHORWE1RjVO6sVwIVN6jkWIgxXZX-oknRiJCszX0oZLqbMEtAc1Cqek8AbKNi61MnqGGjkDtrigfSgjwnDqJIQMsW5vuuQjXwwP2D9sEF0qe9wBGWsfa8qHqFD9Qb24nhQk1wv8Wz65s3w_K1o7knB-2VBHLiDM7X2Vw6jBI0e206BOMh9F3kZLiHUysG6kxEpHWDipZtV_c_czVv6a1EmGqlw-2mZAfqjbl6l5-vl58IoNjfEZW9G-Id1BWk4lrpf11a9zjfkGsRdg1jYZR0c_QKNPwr4z6jZ7NUIhA - - - 404 0 - 0.2309ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
```

### Expected Result

Successful Login

### Actual Result

Login not successful -  404 error 

### Chart Version

0.1.2-Beta

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by bubylou** [comment]
Are you referring to the official Bitwarden website? I'm guessing you are by the link you provided. This repo is for a helm chart to support self hosting your own bitwarden server. For support on the offical website try this link [Help](https://bitwarden.com/help).

**Comment by hegedussz** [comment]
> @hegedussz are you referring to the official Bitwarden website? I'm guessing you are by the link you provided. This repo is for a helm chart to support self hosting your own bitwarden server. For support on the offical website try this link [Help](https://bitwarden.com/help).

No, I use self-hosted Bitwarden. 
I used this Helm Chart for the setup

**Comment by jhbeskow** [comment]
Thank you for reporting.  We are currently working through a redirect issue with SSO.

**Comment by jhbeskow** [comment]
@hegedussz , are you using NGINX?  If so, can you try the updated path and annotation settings found in this PR? #77

**Comment by vgrassia** [comment]
The [self-host-0.1.10-Beta](https://github.com/bitwarden/helm-charts/releases/tag/self-host-0.1.10-Beta) release should fix this.
